### ISSUE TITLE
Have you heard of deno-args ?

### ISSUE THREAD

**Issue by garronej** [siokas/denomander#11]
Hi, 

Allow me to give you a little feedback, do with it what you want, feel free to ignore.

The quality of the code you produce is very good but I think the main problem with commander.js is that it was designed for vanilla JavaScript. Its API design does not allow type inference...

Maybe you should keep the ``denomander`` name and the logo which is really cool and join forces with u/KSXGitHub to work on https://github.com/KSXGitHub/deno-args which look really promising.

I think for commander.js a simple fork using [denoify](https://github.com/garronej/denoify) to make it cross-compatible is enough. 

However, what you did is cool.

Cheers

**Comment by siokas** [comment]
Hi,

I see your point and in a way I agree but I have some ideas regarding the future of the project that goes beyond the usage of the commander.js .

Thank you very much for the advice and the kind words. I think that I should talk with u/KSXGitHub and maybe join forces in some level!

Cheers
