### ISSUE TITLE
Required arguments cannot be hyphenated

### ISSUE THREAD

**Issue by jameskirkwood** [siokas/denomander#15]
The following program complains, `Required option is not specified!`, even when it is. As far as I can tell, it has to do with the presence of a hyphen in the option.

```typescript
import Denomander from "https://deno.land/x/denomander/mod.ts";

new Denomander({ app_name: '', app_description: '', app_version: '' })
    .requiredOption('--hyphenated-option', '')
    .parse(Deno.args);
```

Also, in case I might be preemptive, I suggest only using the `invalid` issue label for irrelevant issues, as suggested [here](https://help.github.com/en/github/managing-your-work-on-github/about-labels#using-default-labels).

**Comment by siokas** [comment]
Yes there was a problem for all hyphenated options. It is fixed now. 

Thank you very much!
