### ISSUE TITLE
Required options scope are program wise instead of command wise

### ISSUE THREAD

**Issue by Willovent** [siokas/denomander#17]
When a required options is set for a command, it must be provide for all commands instead of just the one adding it 

```
deno run https://raw.githubusercontent.com/siokas/denomander/master/example.ts clone folder
```
outputs : _`Error: Required option is not specified!`_

```
deno run https://raw.githubusercontent.com/siokas/denomander/master/example.ts clone folder -p 8080
```
outputs:  _`The repo is cloned into: folder`_

**Comment by siokas** [comment]
In next release, I plan to make every option to belong on a specific command. So every option (including required options) are going to be command wise. 

I inspired from laravel's artisan commands to to so. 
Do you think that this is not needed and options should be program wise?

**Comment by Willovent** [comment]
I think this is needed and it's great to see it's already on your todo !
