### ISSUE TITLE
Property 'reset' does not exist on type 'Option'

### ISSUE THREAD

**Issue by PabloSzx** [siokas/denomander#18]
![image](https://user-images.githubusercontent.com/8672915/82344435-0c763500-99c2-11ea-812b-849236776f86.png)

![image](https://user-images.githubusercontent.com/8672915/82344494-1b5ce780-99c2-11ea-996a-76310de08046.png)

**Comment by siokas** [comment]
Accidentally I have deleted a method for reseting base options. Now it is fixed!
