### ISSUE TITLE
Optional command arguments

### ISSUE THREAD

**Issue by halvardssm** [siokas/denomander#21]
Hi! Is there a way to allow for optional arguments? 

Right now, if I use command
`program.command("command [value]")`
it will result in an error if I don't provide a value. 

However, I would like to have this value optional, is this possible in the current version?

**Comment by siokas** [comment]
Hi. Yes it is possible in current version. You just have to add a question mark after the declaration of the argument. There is such an example in examle/example.ts file.

```javascript
program
  .command("mv [from] [to] [message?]")
  .action(({ from, to, message }: any) => {
    colored_output(`File is moved from ${from} to ${to}`);
    if (message) {
      console.log(message);
    }
  }).description("move file");
```

**Comment by halvardssm** [comment]
Thanks! I must have missed that! 👍
