### ISSUE TITLE
improved error experience

### ISSUE THREAD

**Issue by hkong** [siokas/denomander#25]
It would be really nice when an error occurs to show the following instead of what is there now:

`Error: You specified an option (--https) that is not defined for the command (serve).`

or something more like bash

`serve: illegal option -- https`
`usage: serve [-ap]`

This would be much cleaner for the end user.  The current error made me think that there was an error in my code, when the error was actually in the command line I typed.

Excellent module by the way!

**Comment by siokas** [comment]
Fixed on 4d93720b737216efa22063834177d18d910b881c
