### ISSUE TITLE
Add version to deno.land/x

### ISSUE THREAD

**Issue by halvardssm** [siokas/denomander#34]
Hi @siokas ! 

I am using Denomander for [Nessie](https://github.com/halvardssm/deno-nessie/), but I prefer to use deno.land/x over nest.land to keep it as vanilla as possible. Could you add the new version tags to the package at deno.land/x ?

Thank you for your work with this package!

**Comment by siokas** [comment]
Hi!
Thank you for remind me, I forgot to add the webhook.
Now its on the latest release
