### ISSUE TITLE
Can not specify a description for arguments

### ISSUE THREAD

**Issue by JohannesRudolph** [siokas/denomander#37]
I took a quick look at the API and also into `printCommandHelp`  and figured there's no way to specify a description for an argument. This is a bit of a bummer because it limits the usefulness of the generated help text

```text
Description:
Transform service instances using specified handlers

Command Usage:
transform [path] {Options}

Arguments:
path

Required Options:
-o --out 	 Path to the out repo

Options:
-h --help 	 Help Screen 	 
```

It would be great if we could specify the same kind of description as for options.

**Comment by siokas** [comment]
Feature added in 4ac00b3bb5b5dc5999f6eba0ad6355b747d5af89. Thanx for the suggestion!!!
