### ISSUE TITLE
Cannot use options with name "action"

### ISSUE THREAD

**Issue by timo-klarshift** [siokas/denomander#46]
When using .option("-a --action", "Name of Action") how can i get hold of the option value? It gets overwritten by the action function itself ... In general i dont think its a good idea to expose the options on the program object itself. Why not make everything available at the first param of the action callback ?

**Comment by siokas** [comment]
Hi!
```typescript
program
  .command("foo")
  .option("-a --action", "action option test")
  .action(() => {
    console.log(program.action);
  });
```

to the above example if I run 
`deno run example.ts foo -a bar`
it gives be the right result.

Where is your problem exactly? Please share your code
