### ISSUE TITLE
why 3 legs?

### ISSUE THREAD

**Issue by felixsanz** [siokas/denomander#47]
why the dino in the logo has 3 legs? why not 2 or 4? if you draw the back side of the front right leg, why not also for the back leg?

![image](https://user-images.githubusercontent.com/6182099/154270259-5aba28c6-4d8f-42a6-8fc7-ccc35977d245.png)

**Comment by siokas** [comment]
😆😂. Nice question. I suppose that the one leg is exactly in front of the other...
